-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN', 'EDITOR');
CREATE TYPE "BookingStatus" AS ENUM ('DRAFT', 'CONFIRMED', 'CANCELLED');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED');

CREATE TABLE "User" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "name" TEXT NOT NULL, "role" "Role" NOT NULL DEFAULT 'USER', "locale" TEXT NOT NULL DEFAULT 'EN', "currency" TEXT NOT NULL DEFAULT 'INR', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Region" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, CONSTRAINT "Region_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Country" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "regionId" TEXT NOT NULL, CONSTRAINT "Country_pkey" PRIMARY KEY ("id"));
CREATE TABLE "State" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "countryId" TEXT NOT NULL, CONSTRAINT "State_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Category" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, CONSTRAINT "Category_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Season" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, CONSTRAINT "Season_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Destination" ("id" TEXT NOT NULL, "slug" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "longDescription" TEXT, "knownFor" JSONB NOT NULL, "bestFor" JSONB NOT NULL, "vibe" TEXT, "budgetLevel" TEXT, "approximateBudget" TEXT, "dailyBudget" TEXT, "idealDuration" TEXT, "weather" TEXT, "activities" JSONB NOT NULL, "attractions" JSONB NOT NULL, "localFood" JSONB NOT NULL, "culture" JSONB NOT NULL, "experiences" JSONB NOT NULL, "transport" JSONB NOT NULL, "safety" TEXT, "accessibility" TEXT, "latitude" DOUBLE PRECISION, "longitude" DOUBLE PRECISION, "rating" DOUBLE PRECISION NOT NULL DEFAULT 0, "regionId" TEXT, "countryId" TEXT, "stateId" TEXT, "categoryId" TEXT, "seasonId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Destination_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DestinationImage" ("id" TEXT NOT NULL, "url" TEXT NOT NULL, "alt" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL DEFAULT 0, "destinationId" TEXT NOT NULL, CONSTRAINT "DestinationImage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DestinationVideo" ("id" TEXT NOT NULL, "url" TEXT NOT NULL, "thumbnail" TEXT, "title" TEXT NOT NULL, "destinationId" TEXT NOT NULL, CONSTRAINT "DestinationVideo_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Activity" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "destinationId" TEXT NOT NULL, CONSTRAINT "Activity_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Attraction" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "destinationId" TEXT NOT NULL, CONSTRAINT "Attraction_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Hotel" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "city" TEXT NOT NULL, "demoRate" TEXT NOT NULL, "rating" DOUBLE PRECISION NOT NULL DEFAULT 0, CONSTRAINT "Hotel_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TransportOption" ("id" TEXT NOT NULL, "type" TEXT NOT NULL, "from" TEXT NOT NULL, "to" TEXT NOT NULL, "duration" TEXT NOT NULL, "demoCost" TEXT NOT NULL, CONSTRAINT "TransportOption_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Route" ("id" TEXT NOT NULL, "from" TEXT NOT NULL, "to" TEXT NOT NULL, "distance" TEXT NOT NULL, "duration" TEXT NOT NULL, "options" JSONB NOT NULL, CONSTRAINT "Route_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Trip" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "startDate" TIMESTAMP(3), "endDate" TIMESTAMP(3), "travellers" INTEGER NOT NULL DEFAULT 1, "style" TEXT, "budget" TEXT, "status" "BookingStatus" NOT NULL DEFAULT 'DRAFT', "userId" TEXT NOT NULL, "destinationId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Trip_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TripDay" ("id" TEXT NOT NULL, "dayNumber" INTEGER NOT NULL, "title" TEXT NOT NULL, "activities" JSONB NOT NULL, "estimatedCost" TEXT, "distance" TEXT, "tripId" TEXT NOT NULL, CONSTRAINT "TripDay_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Booking" ("id" TEXT NOT NULL, "reference" TEXT NOT NULL, "status" "BookingStatus" NOT NULL DEFAULT 'DRAFT', "userId" TEXT NOT NULL, "tripId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Booking_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Payment" ("id" TEXT NOT NULL, "transactionId" TEXT NOT NULL, "amount" INTEGER NOT NULL, "currency" TEXT NOT NULL, "method" TEXT NOT NULL, "status" "PaymentStatus" NOT NULL DEFAULT 'PENDING', "demoMode" BOOLEAN NOT NULL DEFAULT true, "bookingId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Payment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PaymentReceipt" ("id" TEXT NOT NULL, "receiptNumber" TEXT NOT NULL, "paymentId" TEXT NOT NULL, "payload" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PaymentReceipt_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Review" ("id" TEXT NOT NULL, "rating" INTEGER NOT NULL, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "travelDate" TIMESTAMP(3), "photoUrl" TEXT, "helpful" INTEGER NOT NULL DEFAULT 0, "userId" TEXT NOT NULL, "destinationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Review_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SavedDestination" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "destinationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SavedDestination_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PackingList" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "userId" TEXT NOT NULL, "destination" TEXT NOT NULL, "duration" INTEGER NOT NULL, "season" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PackingList_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PackingItem" ("id" TEXT NOT NULL, "label" TEXT NOT NULL, "category" TEXT NOT NULL, "packed" BOOLEAN NOT NULL DEFAULT false, "listId" TEXT NOT NULL, CONSTRAINT "PackingItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Budget" ("id" TEXT NOT NULL, "currency" TEXT NOT NULL DEFAULT 'INR', "travellers" INTEGER NOT NULL, "duration" INTEGER NOT NULL, "userId" TEXT NOT NULL, "tripId" TEXT NOT NULL, CONSTRAINT "Budget_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Expense" ("id" TEXT NOT NULL, "category" TEXT NOT NULL, "label" TEXT NOT NULL, "amount" INTEGER NOT NULL, "budgetId" TEXT NOT NULL, CONSTRAINT "Expense_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "message" TEXT NOT NULL, "read" BOOLEAN NOT NULL DEFAULT false, "userId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AIConversation" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "userId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AIConversation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AIMessage" ("id" TEXT NOT NULL, "role" TEXT NOT NULL, "content" TEXT NOT NULL, "conversationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AIMessage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AnalyticsEvent" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "path" TEXT, "metadata" JSONB, "userId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AnalyticsEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SearchHistory" ("id" TEXT NOT NULL, "query" TEXT NOT NULL, "userId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SearchHistory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "UserPreference" ("id" TEXT NOT NULL, "language" TEXT NOT NULL DEFAULT 'EN', "theme" TEXT NOT NULL DEFAULT 'light', "textSize" TEXT NOT NULL DEFAULT 'normal', "highContrast" BOOLEAN NOT NULL DEFAULT false, "reducedMotion" BOOLEAN NOT NULL DEFAULT false, "userId" TEXT NOT NULL, CONSTRAINT "UserPreference_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Region_name_key" ON "Region"("name");
CREATE UNIQUE INDEX "Country_name_key" ON "Country"("name");
CREATE UNIQUE INDEX "Category_name_key" ON "Category"("name");
CREATE UNIQUE INDEX "Season_name_key" ON "Season"("name");
CREATE UNIQUE INDEX "Destination_slug_key" ON "Destination"("slug");
CREATE UNIQUE INDEX "Booking_reference_key" ON "Booking"("reference");
CREATE UNIQUE INDEX "Payment_transactionId_key" ON "Payment"("transactionId");
CREATE UNIQUE INDEX "Payment_bookingId_key" ON "Payment"("bookingId");
CREATE UNIQUE INDEX "PaymentReceipt_receiptNumber_key" ON "PaymentReceipt"("receiptNumber");
CREATE UNIQUE INDEX "PaymentReceipt_paymentId_key" ON "PaymentReceipt"("paymentId");
CREATE UNIQUE INDEX "SavedDestination_userId_destinationId_key" ON "SavedDestination"("userId", "destinationId");
CREATE UNIQUE INDEX "Budget_tripId_key" ON "Budget"("tripId");
CREATE UNIQUE INDEX "UserPreference_userId_key" ON "UserPreference"("userId");

ALTER TABLE "Country" ADD CONSTRAINT "Country_regionId_fkey" FOREIGN KEY ("regionId") REFERENCES "Region"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "State" ADD CONSTRAINT "State_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "Country"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Destination" ADD CONSTRAINT "Destination_regionId_fkey" FOREIGN KEY ("regionId") REFERENCES "Region"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Destination" ADD CONSTRAINT "Destination_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "Country"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Destination" ADD CONSTRAINT "Destination_stateId_fkey" FOREIGN KEY ("stateId") REFERENCES "State"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Destination" ADD CONSTRAINT "Destination_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Destination" ADD CONSTRAINT "Destination_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES "Season"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "DestinationImage" ADD CONSTRAINT "DestinationImage_destinationId_fkey" FOREIGN KEY ("destinationId") REFERENCES "Destination"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DestinationVideo" ADD CONSTRAINT "DestinationVideo_destinationId_fkey" FOREIGN KEY ("destinationId") REFERENCES "Destination"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Trip" ADD CONSTRAINT "Trip_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Trip" ADD CONSTRAINT "Trip_destinationId_fkey" FOREIGN KEY ("destinationId") REFERENCES "Destination"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TripDay" ADD CONSTRAINT "TripDay_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PaymentReceipt" ADD CONSTRAINT "PaymentReceipt_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Review" ADD CONSTRAINT "Review_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Review" ADD CONSTRAINT "Review_destinationId_fkey" FOREIGN KEY ("destinationId") REFERENCES "Destination"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SavedDestination" ADD CONSTRAINT "SavedDestination_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SavedDestination" ADD CONSTRAINT "SavedDestination_destinationId_fkey" FOREIGN KEY ("destinationId") REFERENCES "Destination"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PackingList" ADD CONSTRAINT "PackingList_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PackingItem" ADD CONSTRAINT "PackingItem_listId_fkey" FOREIGN KEY ("listId") REFERENCES "PackingList"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Budget" ADD CONSTRAINT "Budget_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Budget" ADD CONSTRAINT "Budget_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_budgetId_fkey" FOREIGN KEY ("budgetId") REFERENCES "Budget"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AIConversation" ADD CONSTRAINT "AIConversation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AIMessage" ADD CONSTRAINT "AIMessage_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "AIConversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SearchHistory" ADD CONSTRAINT "SearchHistory_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "UserPreference" ADD CONSTRAINT "UserPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
